on:
  push:
    branches: main

name: pkgdown

jobs:
  pkgdown:
    uses: BristolMyersSquibb/blockr.ci/.github/workflows/pkgdown.yaml@v0.1.1
    secrets: inherit
    permissions:
      contents: write
